#!/usr/bin/env bash
# Prove a Trivy scan actually ran, rather than trusting a green step.
#
# Both Trivy jobs use `exit-code: "0"` (report-only), so the step passes
# whatever happens. Combined with the previous breakage — an unresolvable action
# ref meant neither scan ever executed — a green job was not evidence of
# anything. This turns "the step didn't fail" into "the scanner produced a
# report".
#
# A clean scan is a legitimate outcome: zero results is fine and does not fail
# here. What fails is the absence of a report, or a report with no runs, which
# means the scanner did not execute.
#
# Usage: check-sarif.sh <sarif-file> <label>
set -uo pipefail

FILE="${1:?sarif file required}"
LABEL="${2:-scan}"

if [ ! -f "$FILE" ]; then
  echo "::error::${LABEL}: no SARIF at ${FILE} — the scan did not run"
  exit 1
fi

if [ ! -s "$FILE" ]; then
  echo "::error::${LABEL}: SARIF at ${FILE} is empty — the scan did not complete"
  exit 1
fi

python3 - "$FILE" "$LABEL" <<'PY'
import json, sys

path, label = sys.argv[1], sys.argv[2]

try:
    with open(path) as fh:
        doc = json.load(fh)
except Exception as exc:
    print(f"::error::{label}: SARIF is not valid JSON ({exc})")
    sys.exit(1)

runs = doc.get("runs") or []
if not runs:
    print(f"::error::{label}: SARIF has no runs[] — the scanner produced no report")
    sys.exit(1)

total_results = 0
tools = []
for run in runs:
    driver = ((run.get("tool") or {}).get("driver") or {})
    name = driver.get("name", "<unnamed>")
    tools.append(name)
    rules = driver.get("rules") or []
    results = run.get("results") or []
    total_results += len(results)
    print(f"{label}: tool={name} rules={len(rules)} results={len(results)}")

# Guards against a report generated by something other than the scanner we
# think we configured.
if not any("trivy" in t.lower() for t in tools):
    print(f"::error::{label}: no Trivy run in SARIF (tools: {', '.join(tools) or 'none'})")
    sys.exit(1)

if total_results == 0:
    print(f"::notice::{label}: scan ran and reported no HIGH/CRITICAL findings")
else:
    print(f"::notice::{label}: scan ran and reported {total_results} HIGH/CRITICAL finding(s)")
PY
